### ISSUE TITLE
How to implement?

### ISSUE THREAD

**Issue by ramsy-nl** [Nerzal/gocloak-echo#11]
Hi,

Since I'm still learning Go I'm curious how this actually is implemented.
Do you have a simple example available on how to configure the middleware?

Thanks!

**Comment by Nerzal** [comment]
Hi, 

well, when using the echo http server, you simply append the functions provided by the interface as middleware. 
The only configuration is done, by passing a gocloak instance and the realm in the constructor function of that package. 

I personally don't use this lib anymore for 2 reasons: 

1. I'm not using echo anymore, cause it does not meet my performance criteria. I do recommend frameworks that built on top of fasthttps like [atreugo](https://github.com/savsgio/atreugo)
2. We are handling token validation and extraction of claims in a more customized way in self written middlewares now. Which is pretty easy to implement by just using the DecodeToken or DecodeTokenCustomClaims functions from gocloak.

**Comment by ramsy-nl** [comment]
Hi @Nerzal,

Thanks for the quick reply and tips. I'll make sure to check out atreugo.
